name: unit tests
on: push
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16.18.0'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test:unit
